# Used only if you use kind to run Kubernetes.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
# - role: worker
networking:
  apiServerAddress: "0.0.0.0" # Note: This setup is easy but not secure.
